/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apptest1;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author vgcga
 */
public class main extends javax.swing.JFrame {
    int sgame = 0;
    int rgame = 0;
    int pgame = 0;
    String[] game_picture;
    String[] game_names;
    String[] game_reviews;
    /**
     * Creates new form main
     */
    public main() {        
        initComponents();
        addListeners();
        
        //Game pictures variables for the array.
        game_picture = new String[12];
        game_picture[0] = "arrow-right.png";
        game_picture[1] = "";
        game_picture[2] = "";
        game_picture[3] = "";
        game_picture[4] = "";
        game_picture[5] = "";
        game_picture[6] = "";
        game_picture[7] = "";
        game_picture[8] = "";
        game_picture[9] = "";
        game_picture[10] = "";
        game_picture[11] = "";
        
        //Game review variables for the array.
        game_reviews = new String[12];
        game_reviews[0] = "*****";
        game_reviews[1] = "***";
        game_reviews[2] = "****";
        game_reviews[3] = "*****";
        game_reviews[4] = "**";
        game_reviews[5] = "*";
        game_reviews[6] = "***";
        game_reviews[7] = "****";
        game_reviews[8] = "*****";
        game_reviews[9] = "***";
        game_reviews[10] = "**";
        game_reviews[11] = "*****";
        
        //Game names variables for the array.
        game_names = new String[12];
        game_names[1] = ("PacMan");
        game_names[2] = ("Super Mario");
        game_names[3] = ("Tetris");
        game_names[4] = ("Pong");
        game_names[5] = ("Space Invaders");
        game_names[6] = ("Brick Breaker");
        game_names[7] = ("Memory Game");
        game_names[8] = ("Lemmings");
        game_names[9] = ("Game #1");
        game_names[10] = ("Game #2");
        game_names[11] = ("NHC");
        
    }
     private void addListeners()
    {
       right_arrow.addMouseListener(new java.awt.event.MouseAdapter() // Adds a listener to the right button.
       {
           public void mouseClicked(java.awt.event.MouseEvent evt) 
       {
               if (sgame == 11){
                   sgame = 0;
                   rgame = 0;
                   pgame = 0;
               } else {
                   sgame++;
                   rgame++;
                   pgame++;
                   System.out.println("Selected: " + sgame);
                   menu_game_name_label.setText(game_names[sgame]);
                   menu_game_review_label.setText(game_reviews[rgame]);
                   
               }
       }
     });
       left_arrow.addMouseListener(new java.awt.event.MouseAdapter()
               {
                   public void mouseClicked(java.awt.event.MouseEvent evt)
               {
                   if (sgame == -1){
                   sgame = 0;
                   rgame = 0;
                   pgame = 0;
               } else {
                   sgame--;
                   rgame--;
                   pgame--;
                   System.out.println("Selected: " + sgame);
                   menu_game_name_label.setText(game_names[sgame]);
                   menu_game_review_label.setText(game_reviews[rgame]);
               }
               }
                   
               });
       
   }
    

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        menu_wallpaper = new javax.swing.JPanel();
        menu_game_review = new javax.swing.JLabel();
        menu_game_name = new javax.swing.JLabel();
        menu_game_review_label = new javax.swing.JLabel();
        menu_game_name_label = new javax.swing.JLabel();
        left_arrow = new javax.swing.JButton();
        right_arrow = new javax.swing.JButton();
        menu_game_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Old School Games APK");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(26, 79, 99));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setResizable(false);
        setSize(new java.awt.Dimension(414, 736));

        menu_wallpaper.setBackground(new java.awt.Color(232, 221, 217));
        menu_wallpaper.setMaximumSize(new java.awt.Dimension(414, 736));
        menu_wallpaper.setName(""); // NOI18N
        menu_wallpaper.setPreferredSize(new java.awt.Dimension(414, 736));

        menu_game_review.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menu_game_review.setText("Review:");

        menu_game_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menu_game_name.setText("Name:");

        menu_game_review_label.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        menu_game_review_label.setText("N/A");

        menu_game_name_label.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        menu_game_name_label.setText("N/A");

        left_arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apptest1/arrow-left.png"))); // NOI18N

        right_arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apptest1/arrow-right.png"))); // NOI18N

        menu_game_image.setText("N/A");

        javax.swing.GroupLayout menu_wallpaperLayout = new javax.swing.GroupLayout(menu_wallpaper);
        menu_wallpaper.setLayout(menu_wallpaperLayout);
        menu_wallpaperLayout.setHorizontalGroup(
            menu_wallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_wallpaperLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(menu_wallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_wallpaperLayout.createSequentialGroup()
                        .addComponent(menu_game_review)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_game_review_label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(menu_wallpaperLayout.createSequentialGroup()
                        .addGroup(menu_wallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menu_wallpaperLayout.createSequentialGroup()
                                .addComponent(menu_game_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menu_game_name_label)
                                .addGap(2, 2, 2))
                            .addComponent(menu_game_image, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(112, Short.MAX_VALUE))
                    .addGroup(menu_wallpaperLayout.createSequentialGroup()
                        .addComponent(left_arrow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(right_arrow)
                        .addGap(57, 57, 57))))
        );
        menu_wallpaperLayout.setVerticalGroup(
            menu_wallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_wallpaperLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(menu_game_image, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(menu_wallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(right_arrow)
                    .addComponent(left_arrow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menu_wallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_game_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_game_name_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menu_wallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_game_review, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_game_review_label))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_wallpaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu_wallpaper, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
                 
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);             
                
            }
        });
    }

    
    // Variables declaration - do not modify                     
    public static javax.swing.JButton left_arrow;
    public static javax.swing.JLabel menu_game_image;
    public static javax.swing.JLabel menu_game_name;
    public static javax.swing.JLabel menu_game_name_label;
    public static javax.swing.JLabel menu_game_review;
    public static javax.swing.JLabel menu_game_review_label;
    public static javax.swing.JPanel menu_wallpaper;
    public static javax.swing.JButton right_arrow;
    // End of variables declaration                   
}

